improve autotool
zeroeightysix/KAMI pull request #312
Opened 2020-11-28 13:42 UTC by LordMZTE

autotool will now always select the correct tool, also for special cases like bamboo by using the same method as the game for calculating the break speed

2020-11-28 13:43 UTC, LordMZTE commented
closes #306

2020-11-30 22:02 UTC, zeroeightysix requested changes

2020-11-30 22:02 UTC, zeroeightysix commented on src/main/kotlin/me/zeroeightsix/kami/feature/module/AutoTool.kt
> +            equip(i, false)
Instead of placing a comment, just explicitly specify `updateServer`: `equip(i, updateServer = false)`. It is more concise.

2020-11-30 22:02 UTC, zeroeightysix commented on src/main/kotlin/me/zeroeightsix/kami/feature/module/AutoTool.kt
> +            val delta = blockState.block.calcBlockBreakingDelta(blockState, mc.player, mc.world, blockPos)
If it's marked deprecated, I wouldn't be surprised if it disappears in a version to come. However, for now, instead of taking a jab at mojang, let's just suppress the warning:
```suggestion
            @Suppress("DEPRECATION")
            val delta = blockState.block.calcBlockBreakingDelta(blockState, mc.player, mc.world, blockPos)
```

2020-11-30 22:02 UTC, zeroeightysix commented on src/main/kotlin/me/zeroeightsix/kami/feature/module/AutoTool.kt
> +            { (it.item as? AxeItem)?.attackDamage })
```suggestion
        SWORD(SwordItem::class.java, { (it.item as? SwordItem)?.attackDamage }),
        AXE(AxeItem::class.java, { (it.item as? AxeItem)?.attackDamage })
```

2020-12-01 19:36 UTC, zeroeightysix approved these changes
Thanks!

2020-12-01 19:36 UTC, merged