Added hclip command
zeroeightysix/KAMI pull request #530
Opened 2021-02-15 10:15 UTC by sALTaccount

added an hclip command, it's similar to vclip but it teleports horizontally instead of vertically

2021-02-15 10:28 UTC, zeroeightysix commented
It is far easier to not restrict hclip to the 4 cardinal directions, and use the player's yaw instead.

You can get a `Vec3d` of the player's facing direction quite easily using `Vec3d.fromPolar`:
```kotlin
val direction = Vec3d.fromPolar(0f, yaw)
```
using that, your entire `when` clause becomes:
```kotlin
updatePosition(
    x + direction.x * blocks,
    y,
    z + direction.z * blocks
)
```

2021-02-15 10:57 UTC, sALTaccount commented
fixed

2021-02-15 14:51 UTC, l1ving commented
Wouldn't it be more useful to also have a vclip command?

2021-02-15 14:58 UTC, zeroeightysix commented
> Wouldn't it be more useful to also have a vclip command?

There is one. Consider looking before you comment. It would, however, be a good idea to merge the two into one command that does both.

2021-02-15 15:11 UTC, l1ving commented
Wasn't aware of that, huh

2021-02-15 15:33 UTC, zeroeightysix requested changes

2021-02-15 15:33 UTC, zeroeightysix commented on src/main/kotlin/me/zeroeightsix/kami/feature/command/HClipCommand.kt
> +                            it.z + direction.z * ("blocks".from<Float, CommandSource>(ctx))
Un-inline `blocks`:
```kt
val blocks: Float = "blocks" from ctx
it.updatePosition(...)
```

2021-02-15 23:36 UTC, sALTaccount commented
I changed it to use a variable for distance. Also, I don't think vclip and hclip should be merged into a singular module. Most utility mods that have vclip and hclip have them as separate commands so I think that we should as well in order to maintain consistency.

2021-03-06 23:28 UTC, zeroeightysix approved these changes
Thanks!

2021-03-06 23:29 UTC, merged